apiVersion: v1
metadata:
  name: {{ include "metabase.fullname" . }}-secrets
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
type: Opaque
stringData:
  MB_DB_HOST: {{ .Values.secrets.database.host | quote }}
  MB_DB_PASS: {{ .Values.secrets.database.password | quote }}
  MB_DB_USER: {{ .Values.secrets.database.username | quote }}
  MB_DB_DBNAME: {{ .Values.secrets.database.dbName | quote }}
  MB_DB_PORT: {{ .Values.secrets.database.port | quote }}
  MB_ENCRYPTION_SECRET_KEY: {{ .Values.secrets.config.encryptionKey | quote }}
  MB_DB_CONNECTION_URI: {{ .Values.secrets.database.connString | quote }}
kind: Secret